{
 "title": "Demo Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Total Participants",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS total_participants\r\nFROM participants;\r\n"
    }
   ]
  },
  {
   "title": "Total Transactions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS total_transactions FROM transfers;\r\n"
    }
   ]
  },
  {
   "title": "Total Pending Transfers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS total_pending_transfers\r\nFROM transfers\r\nWHERE state IN ('RECEIVED', 'VALIDATED', 'RESERVED', 'ACKNOWLEDGED', 'CONFIRMED');\r\n"
    }
   ]
  },
  {
   "title": "Participants Balance",
   "type": "table",
   "gridPos": { "h": 16, "w": 6, "x": 11, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT name, balance\r\nFROM participants;\r\n"
    }
   ]
  },
  {
   "title": "Total ABORTED Transfers per Participant",
   "type": "table",
   "gridPos": { "h": 16, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT p.name AS participant_name, COUNT(t.id) AS aborted_transfer_count\r\nFROM participants p\r\nLEFT JOIN transfers t ON p.id = t.participant_id\r\nWHERE t.state = 'ABORTED'\r\nGROUP BY p.id\r\norder by 2 desc"
    }
   ]
  },
  {
   "title": "Pending Transfers in Different States",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 5, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT state, COUNT(*) AS transfer_count\r\nFROM transfers\r\nWHERE state IN ('RECEIVED', 'VALIDATED', 'RESERVED', 'ACKNOWLEDGED', 'CONFIRMED')\r\nGROUP BY state;\r\n"
    }
   ]
  },
  {
   "title": "Pending Transfers for Each Participant",
   "type": "table",
   "gridPos": { "h": 13, "w": 6, "x": 5, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT p.name AS participant_name, COUNT(t.id) AS pending_transfer_count\r\nFROM participants p\r\nLEFT JOIN transfers t ON p.id = t.participant_id\r\nWHERE t.state IN ('RECEIVED', 'VALIDATED', 'RESERVED', 'ACKNOWLEDGED', 'CONFIRMED')\r\nGROUP BY p.id;"
    }
   ]
  },
  {
   "title": "Participants Balance",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT name, balance\r\nFROM participants"
    }
   ]
  }
 ]
}